version: "3"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on:
      - redis


